// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvaymmretdpfzulxxlnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2YXltbXJldGRwZnp1bHh4bG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjA4NjUsImV4cCI6MjA3MjA5Njg2NX0.a_zvWVRGTVBEBa0btmeKA0s4sOZvAsskRQY2VQp8bIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});